name: 'GitHub Secrets Exporter'
description: 'Securely export repository secrets encrypted with age'
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  public_key_path:
    description: 'Path to age public key file (default: uses your GitHub SSH keys)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install age
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y age

    - name: Export and encrypt all secrets
      shell: bash
      run: |
        # Use age key if specified, otherwise use GitHub SSH keys
        if [ -n "${{ inputs.public_key_path }}" ]; then
          RECIPIENT_FILE="${{ inputs.public_key_path }}"
        else
          curl -sf "https://github.com/${{ github.actor }}.keys" > /tmp/github_keys.txt
          RECIPIENT_FILE=/tmp/github_keys.txt
        fi

        echo "$SECRETS_JSON" | \
          age -R "$RECIPIENT_FILE" | \
          base64 --wrap=0 > /tmp/encrypted-secrets.txt

    - name: Upload encrypted secrets
      uses: actions/upload-artifact@v4
      with:
        name: encrypted-secrets
        path: /tmp/encrypted-secrets.txt
        retention-days: 1

    - name: Show download instructions
      shell: bash
      run: |
        echo "✓ Secrets encrypted and uploaded as artifact"
        echo ""
        echo "Download with:"
        echo "  gh run download ${{ github.run_id }} -n encrypted-secrets"
        echo ""
        echo "Then decrypt:"
        echo "  cat encrypted-secrets.txt | base64 --decode | age --decrypt --identity ~/.ssh/id_ed25519"
        echo ""
        echo "Artifact will auto-delete in 1 day"
