name: 'GitHub Secrets Exporter'
description: 'Securely export repository secrets encrypted with age'
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  public_encryption_key:
    description: 'Your public encryption key (age or SSH format)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install age
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y age

    - name: Export and encrypt all secrets
      shell: bash
      run: |
        # Write public key to temp file
        echo "${{ inputs.public_encryption_key }}" > /tmp/public_key.txt

        echo "$SECRETS_JSON" | \
          age -R /tmp/public_key.txt | \
          base64 --wrap=0 > /tmp/encrypted-secrets.txt

        # Cleanup immediately
        rm -f /tmp/public_key.txt
        unset SECRETS_JSON

    - name: Upload encrypted secrets
      uses: actions/upload-artifact@v4
      with:
        name: encrypted-secrets
        path: /tmp/encrypted-secrets.txt
        retention-days: 1

    - name: Cleanup and show instructions
      shell: bash
      run: |
        # Delete encrypted file from runner
        rm -f /tmp/encrypted-secrets.txt

        echo "✓ Secrets encrypted and uploaded as artifact"
        echo ""
        echo "Download with:"
        echo "  gh run download ${{ github.run_id }} -n encrypted-secrets"
        echo ""
        echo "Then decrypt:"
        echo "  cat encrypted-secrets.txt | base64 --decode | age --decrypt --identity ~/.ssh/id_ed25519"
        echo ""
        echo "Artifact will auto-delete in 1 day"
