name: 'GitHub Secrets Exporter'
description: 'Securely export repository secrets encrypted with age'
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  public_key_path:
    description: 'Path to age public key file (default: uses your GitHub SSH keys)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install age
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y age

    - name: Export and encrypt all secrets
      shell: bash
      run: |
        # Use age key if specified, otherwise use GitHub SSH keys
        if [ -n "${{ inputs.public_key_path }}" ]; then
          RECIPIENT_FILE="${{ inputs.public_key_path }}"
        else
          curl -sf "https://github.com/${{ github.actor }}.keys" > /tmp/github_keys.txt
          RECIPIENT_FILE=/tmp/github_keys.txt
        fi

        echo "=== ENCRYPTED SECRETS (base64) ==="
        echo "$SECRETS_JSON" | \
          age -R "$RECIPIENT_FILE" | \
          base64 --wrap=0
        echo ""
        echo "=== END ==="
